# Generated by Django 4.1.1 on 2022-10-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_ID',
            field=models.CharField(max_length=264, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='student',
            name='experience',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='student',
            name='qualification',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_ID',
            field=models.CharField(max_length=264, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(max_length=264),
        ),
    ]
